# Check if the plugin should be able to automaticly update itself
# Powered by SpigetUpdater (https://github.com/InventivetalentDev/SpigetUpdater)
auto-update: true

# The cost of xp levels for repairing a item
cost: 10

# The message to send to the player
message:
  enabled: true
  text: '&cThe item in your inventory now will have an repair cost of %cost% levels'
  
# Include here the items that are repairable
items: 
  - 'WOOD_SWORD'
  - 'WOOD_SPADE'
  - 'WOOD_HOE'
  - 'WOOD_AXE'
  - 'WOOD_PICKAXE'

  - 'CHAINMAIL_HELMET'
  - 'CHAINMAIL_CHESTPLATE'
  - 'CHAINMAIL_LEGGINGS'
  - 'CHAINMAIL_BOOTS'

  - 'IRON_SWORD'
  - 'IRON_HELMET'
  - 'IRON_CHESTPLATE'
  - 'IRON_LEGGINGS'
  - 'IRON_BOOTS'
  - 'IRON_SPADE'
  - 'IRON_HOE'
  - 'IRON_AXE'
  - 'IRON_PICKAXE'

  - 'GOLD_SWORD'
  - 'GOLD_HELMET'
  - 'GOLD_CHESTPLATE'
  - 'GOLD_LEGGINGS'
  - 'GOLD_BOOTS'
  - 'GOLD_SPADE'
  - 'GOLD_HOE'
  - 'GOLD_AXE'
  - 'GOLD_PICKAXE'

  - 'DIAMOND_SWORD'
  - 'DIAMOND_HELMET'
  - 'DIAMOND_CHESTPLATE'
  - 'DIAMOND_LEGGINGS'
  - 'DIAMOND_BOOTS'
  - 'DIAMOND_SPADE'
  - 'DIAMOND_HOE'
  - 'DIAMOND_AXE'
  - 'DIAMOND_PICKAXE'

  - 'SHIELD'
  - 'ELYTRA'
  - 'CARROT_STICK'
  - 'FLINT_AND_STEEL'
  - 'FISHING_ROD'
  - 'SHEARS'
  - 'BOW'